// packages/solid/src/index.tsx
import sizes from 'virtual:vite-img/sizes';
import { createSignal, splitProps, type ComponentProps } from 'solid-js';
import { isServer } from 'solid-js/web';
import { getSource, getUrl, type ImageProps as CreateImageProps, type SrcImageProps } from '@vite-img/core';

export type ImageProps = CreateImageProps<ComponentProps<'img'>>;

export default function Image(props: ImageProps) {
    const [srcProps, rest] = splitProps(props, ['src', 'width', 'height', 'placeholder']);
    const src = () => getSource(srcProps as SrcImageProps);
    const [isLoading, setLoading] = createSignal(!isServer);
    const quality = () => props.quality ?? 75;

    return (
        <img
            {...rest}
            src={getUrl({ src: src().src, q: quality() })}
            srcSet={sizes.map((size) => `${getUrl({ src: src().src, w: size, q: quality() })} ${size}w`).join(', ')}
            width={src().width}
            height={src().height}
            style={
                src().placeholder != null && isLoading()
                    ? {
                        ...(typeof rest.style === 'object' ? rest.style : {}),
                        "background-image": `url(${src().placeholder})`,
                        "background-size": 'cover',
                        "background-position": '50% 50%',
                        "background-repeat": 'no-repeat',
                      }
                    : rest.style
            }
            onLoad={[() => setLoading(false), props.onLoad]}
            onError={[() => setLoading(false), props.onError]}
        />
    );
}

// packages/vite-img/src/index.tsx
import sizes from "virtual:vite-img/sizes";
import { useState, type ComponentPropsWithoutRef } from "react";

export interface StaticImage {
  src: string;
  width: number;
  height: number;
  blurUrl: string;
}

type StringSrcImageProps = {
  src: string;
  placeholder?: undefined;
  width: number | string;
  height: number | string;
};

type StaticSrcImageProps = {
  src: StaticImage;
  placeholder?: "blur";
  width?: number | string;
  height?: number | string;
};

type ImageOwnProps = (StringSrcImageProps | StaticSrcImageProps) & {
    alt: string;
    quality?: number;
  };

export type ImageProps = Omit<
  ComponentPropsWithoutRef<"img">,
  keyof ImageOwnProps
> &
  ImageOwnProps;

export default function Image({ loading, decoding, quality = 75, style, onLoad, onError, ...props }: ImageProps) {
  const { src, width, height, placeholder } = normalizeSrc(props);
  const [isLoading, setLoading] = useState(true);

  return (
    <img
      {...props}
      src={getURL({ src, q: quality })}
      width={width}
      height={height}
      loading={loading ?? "lazy"}
      decoding={decoding ?? "async"}
      style={
        placeholder != null && isLoading
          ? {
              ...style,
              backgroundImage: `url(${placeholder})`,
              backgroundSize: "cover",
              backgroundPosition: "50% 50%",
              backgroundRepeat: "no-repeat",
            }
          : style
      }
      srcSet={(sizes as number[])
        .map((size) => `${getURL({ src, w: size, q: quality })} ${size}w`)
        .join(", ")}
      onLoad={(event) => {
        setLoading(false);
        onLoad?.(event);
      }}
      onError={(event) => {
        setLoading(false);
        onError?.(event);
      }}
    />
  );
}

interface UrlParams {
  src: string;
  q: number;
  w?: number;
  h?: number;
}

function getURL(params: UrlParams) {
  const searchParams = new URLSearchParams();
  for (const [key, value] of Object.entries(params)) {
    searchParams.set(key, value);
  }
  return `/api/image?${searchParams}`;
}

function normalizeSrc({ src, width, height, placeholder }: StaticSrcImageProps | StringSrcImageProps) {
  return typeof src === "string"
    ? { src, width, height }
    : {
        src: src.src,
        width: width ?? src.width,
        height: height ?? src.height,
        placeholder: placeholder === "blur" ? src.blurUrl : undefined
      };
}
